@startuml

package "Klientská aplikace" as clientApp {

    folder "Views"

    folder "ViewModels"

    folder "Services"

    folder "Animations"

    folder "Controls"

    folder "Constants"

}

package "Aplikace webové API" as webApp {

    folder "Mediator"

    folder "DataAccess"

    folder "Migrations"

    folder "Controllers"

    folder "Pages"

}

package "Sdílená knihovna" as sharedLibrary {

    folder "Models"

}

package "Testy" as tests {

    folder "ServerTests"

    folder "ClientTests"

}

package "Databáze" as db {

    folder "DatabaseTables"

    folder "Indexes"

    folder "Catalog"

}

webApp .up.> sharedLibrary : "<<use>>"

clientApp ..> sharedLibrary : "<<use>>"

clientApp ..> webApp : "<<use>>"

tests .left.> clientApp : "<<use>>"

tests .down.> webApp : "<<use>>"

webApp ..> db : "<<use>>"

@enduml
