@startuml

left to right direction

actor "Provozovatel stánků" as provozovatel

actor "Obchodník se stánky" as obchodnik

actor "Pracovník správy zásob" as zasobnik

actor WMS <<system>>

actor "Sociální sítě" as socialniSite <<system>>

rectangle "Prodejní systém" {

    usecase "UC1: Sledování tržeb" as UC1

    usecase "UC2: Realizace slevových kampaní" as UC2

    usecase "UC3: Posílání aktualizací zásob" as UC3

    usecase "UC4: Integrace se sociálními sítěmi" as UC4

    usecase "UC5: Export dat pro účetní nástroje" as UC5

}

obchodnik --> UC1

obchodnik --> UC2

obchodnik --> UC3

obchodnik --> UC4

obchodnik --> UC5

provozovatel -up-> UC1

provozovatel -up-> UC2

provozovatel -up-> UC4

UC3 <-- WMS

zasobnik <-- UC3

UC4 --> socialniSite

@enduml